name: Update Compose

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.SERVER_SSH_KEY_PUB }}" > ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519*
          ssh-keyscan -p "${{ secrets.SERVER_PORT }}" "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts
      - name: docker compose pull and re-up
        run: |
          ssh -o StrictHostKeyChecking=yes -p "${{ secrets.SERVER_PORT }}" "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" << 'EOF'
            docker compose pull
            docker compose up -d
          EOF
